import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version',
};

const categoryMap: Record<string, string> = {
  versiculo: 'versiculo',
  oracao: 'oracao',
  devocional: 'devocional',
  biblia: 'versiculo',
  spiritual: 'destaque',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { type } = await req.json();
    const category = categoryMap[type || 'spiritual'] || 'destaque';

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    // Always return cached image - never generate new ones here
    const { data: cached } = await supabase
      .from('cached_images')
      .select('image_data')
      .eq('category', category)
      .single();

    if (cached?.image_data) {
      return new Response(
        JSON.stringify({ imageUrl: cached.image_data }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
      );
    }

    // Fallback - no cached image available yet (will be generated by daily-notification)
    return new Response(
      JSON.stringify({ imageUrl: '/icon-512.png' }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
    );

  } catch (error) {
    console.error('Error:', error);
    return new Response(
      JSON.stringify({ imageUrl: '/icon-512.png' }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
    );
  }
});
