project_id = "Luzdivina.top"

[functions.ouvindo-deus]
verify_jwt = false

[functions.daily-notification]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.generate-og-image]
verify_jwt = false
